/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet.swing;
import Creation_Objet.Employe;
import DAO.EmployeDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Jules
 */
public class Creation_employe_jpanel extends javax.swing.JPanel {

    /**
     * Creates new form Creation_employe_jpanel
     */
    EmployeDAO empDAO=null;
    
    public Creation_employe_jpanel() {
        initComponents();
    }
    public void setEmployeDAO(EmployeDAO empDAO){
        this.empDAO=empDAO;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        create_emp = new javax.swing.JButton();
        Titre_crea_emp = new javax.swing.JLabel();
        idemp_form = new javax.swing.JTextField();
        idemp_form_text = new javax.swing.JLabel();
        prenom_form = new javax.swing.JTextField();
        nom_form = new javax.swing.JTextField();
        matricule_form = new javax.swing.JTextField();
        prenom_form_text = new javax.swing.JLabel();
        nom_form_text = new javax.swing.JLabel();
        matricule_form_text = new javax.swing.JLabel();
        idbur_form = new javax.swing.JTextField();
        idbur_form_text = new javax.swing.JLabel();

        create_emp.setText("créer");
        create_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_empActionPerformed(evt);
            }
        });

        Titre_crea_emp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titre_crea_emp.setText("Création Employé");

        idemp_form.setEditable(false);
        idemp_form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idemp_formActionPerformed(evt);
            }
        });

        idemp_form_text.setText("idemp :");

        prenom_form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenom_formActionPerformed(evt);
            }
        });

        matricule_form.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        prenom_form_text.setText("Prenom :");

        nom_form_text.setText("Nom :");

        matricule_form_text.setText("Matricule :");

        idbur_form.setToolTipText("");
        idbur_form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idbur_formActionPerformed(evt);
            }
        });

        idbur_form_text.setText("Idbur :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(create_emp)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(Titre_crea_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idemp_form_text, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(matricule_form_text, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(idbur_form_text)
                                .addComponent(prenom_form_text)
                                .addComponent(nom_form_text)))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idemp_form, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(matricule_form)
                            .addComponent(nom_form)
                            .addComponent(prenom_form)
                            .addComponent(idbur_form))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titre_crea_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idemp_form_text)
                    .addComponent(idemp_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matricule_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matricule_form_text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nom_form_text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prenom_form_text)
                    .addComponent(prenom_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idbur_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idbur_form_text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(create_emp)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void create_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_empActionPerformed
        try{
           //int idemp=Integer.parseInt(idemp_form.getText());
           String matricule=matricule_form.getText();
           String nom=nom_form.getText();
           String prenom=prenom_form.getText();
           int idbur=Integer.parseInt(idbur_form.getText());
            Employe emp=new Employe(0,matricule,nom,prenom,idbur);
            emp=empDAO.create(emp);
            idemp_form.setText(""+emp.getIdemp());
            JOptionPane.showMessageDialog(this,"employé créé","succès",JOptionPane.INFORMATION_MESSAGE);

        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage(),"ERREUR",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_create_empActionPerformed
    }
    private void idemp_formActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idemp_formActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idemp_formActionPerformed

    private void prenom_formActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenom_formActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenom_formActionPerformed

    private void idbur_formActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idbur_formActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idbur_formActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titre_crea_emp;
    private javax.swing.JButton create_emp;
    private javax.swing.JTextField idbur_form;
    private javax.swing.JLabel idbur_form_text;
    private javax.swing.JTextField idemp_form;
    private javax.swing.JLabel idemp_form_text;
    private javax.swing.JTextField matricule_form;
    private javax.swing.JLabel matricule_form_text;
    private javax.swing.JTextField nom_form;
    private javax.swing.JLabel nom_form_text;
    private javax.swing.JTextField prenom_form;
    private javax.swing.JLabel prenom_form_text;
    // End of variables declaration//GEN-END:variables
}
