/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet.swing;

import Creation_Objet.Bureau;
import DAO.BureauDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Jules
 */
public class Creation_bureau_jpanel extends javax.swing.JPanel {

    /**
     * Creates new form creation_bureau_jframe
     */
    BureauDAO burDAO=null;
    public Creation_bureau_jpanel() {
        initComponents();
    }
    public void setBureauDAO(BureauDAO burDAO){
        this.burDAO=burDAO;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sigle_form_text = new javax.swing.JLabel();
        tel_form_text = new javax.swing.JLabel();
        desc_form_text = new javax.swing.JLabel();
        sigle_form = new javax.swing.JTextField();
        tel_form = new javax.swing.JTextField();
        desc_form = new javax.swing.JTextField();
        idbur_form_text = new javax.swing.JLabel();
        idbur_form = new javax.swing.JTextField();
        Titre_crea_bur = new javax.swing.JLabel();
        create_bur = new javax.swing.JButton();

        sigle_form_text.setText("Sigle :");

        tel_form_text.setText("Tel :");

        desc_form_text.setText("Description :");

        sigle_form.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        desc_form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desc_formActionPerformed(evt);
            }
        });

        idbur_form_text.setText("idbur :");

        idbur_form.setEditable(false);
        idbur_form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idbur_formActionPerformed(evt);
            }
        });

        Titre_crea_bur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titre_crea_bur.setText("Création Bureau");

        create_bur.setText("créer");
        create_bur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_burActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(create_bur)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(desc_form_text)
                            .addComponent(idbur_form_text, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tel_form_text)
                                .addComponent(sigle_form_text)))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idbur_form, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(sigle_form)
                            .addComponent(tel_form)
                            .addComponent(desc_form)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(Titre_crea_bur, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titre_crea_bur, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idbur_form_text)
                    .addComponent(idbur_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sigle_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sigle_form_text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tel_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tel_form_text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desc_form_text)
                    .addComponent(desc_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(create_bur)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void desc_formActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desc_formActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desc_formActionPerformed

    private void idbur_formActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idbur_formActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idbur_formActionPerformed

    private void create_burActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_burActionPerformed
try{
            //int idbur=Integer.parseInt(idbur_form1.getText());
            String sigle=sigle_form.getText();
            String tel=tel_form.getText();
            String desc=desc_form.getText();
            Bureau bur=new Bureau(0,sigle,tel,desc);
            bur=burDAO.create(bur);
            idbur_form.setText(""+bur.getIdbur());
            JOptionPane.showMessageDialog(this,"bureau créé","succès",JOptionPane.INFORMATION_MESSAGE);

        }catch(Exception e){
                    JOptionPane.showMessageDialog(this,e.getMessage(),"ERREUR",JOptionPane.ERROR_MESSAGE);
}    }//GEN-LAST:event_create_burActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titre_crea_bur;
    private javax.swing.JButton create_bur;
    private javax.swing.JTextField desc_form;
    private javax.swing.JLabel desc_form_text;
    private javax.swing.JTextField idbur_form;
    private javax.swing.JLabel idbur_form_text;
    private javax.swing.JTextField sigle_form;
    private javax.swing.JLabel sigle_form_text;
    private javax.swing.JTextField tel_form;
    private javax.swing.JLabel tel_form_text;
    // End of variables declaration//GEN-END:variables
}
