/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet.swing;

import DAO.BureauDAO;
import java.awt.CardLayout;
import java.sql.Connection;
import javax.swing.JOptionPane;
import myconnections.DBConnection;

/**
 *
 * @author Jules
 */
public class gestionBureau extends javax.swing.JFrame {

    /**
     * Creates new form gestionBureau
     */
    CardLayout cardl;
    public gestionBureau() {
        initComponents();
        cardl=(CardLayout)this.getContentPane().getLayout();
        Connection dbConnect = DBConnection.getConnection();
    if (dbConnect == null) {
            System.out.println("connection invalide");
            JOptionPane.showMessageDialog(this,"connexion invalide","ERREUR",JOptionPane.ERROR_MESSAGE);
    }
    BureauDAO burDAO=new BureauDAO();
    burDAO.setConnection(dbConnect);
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creation_bureau_jpanel = new projet.swing.Creation_bureau_jpanel();
        recherche_exacte_bureau_jpanel = new projet.swing.Recherche_exacte_bureau_jpanel();
        recherche_partielle_bureau_jpanel = new projet.swing.Recherche_partielle_bureau_jpanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuBureau = new javax.swing.JMenu();
        itemCreateBureau = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(creation_bureau_jpanel, "cardCreateBureau");
        getContentPane().add(recherche_exacte_bureau_jpanel, "cardRechExactBureau");
        getContentPane().add(recherche_partielle_bureau_jpanel, "cardRechPartBureau");

        menuBureau.setText("Bureau");

        itemCreateBureau.setText("Creer bureau");
        itemCreateBureau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCreateBureauActionPerformed(evt);
            }
        });
        menuBureau.add(itemCreateBureau);

        jMenuItem1.setText("Recherche Exacte");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuBureau.add(jMenuItem1);

        jMenuItem2.setText("Recherche partielle");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuBureau.add(jMenuItem2);

        jMenuBar1.add(menuBureau);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCreateBureauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCreateBureauActionPerformed
        cardl.show(this.getContentPane(), "cardCreateBureau");
    }//GEN-LAST:event_itemCreateBureauActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       cardl.show(this.getContentPane(), "cardRechExactBureau");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       cardl.show(this.getContentPane(),"cardRechPartBureau");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestionBureau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestionBureau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestionBureau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestionBureau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gestionBureau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private projet.swing.Creation_bureau_jpanel creation_bureau_jpanel;
    private javax.swing.JMenuItem itemCreateBureau;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu menuBureau;
    private projet.swing.Recherche_exacte_bureau_jpanel recherche_exacte_bureau_jpanel;
    private projet.swing.Recherche_partielle_bureau_jpanel recherche_partielle_bureau_jpanel;
    // End of variables declaration//GEN-END:variables
}
