/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet.swing;

import Creation_Objet.Employe;
import DAO.EmployeDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Jules
 */
public class Recherche_exacte_employe_jpanel extends javax.swing.JPanel {

    /**
     * Creates new form Recherche_exacte_employe_jpanel
     */
    EmployeDAO empDAO=null;
    Employe emp=null;
    public Recherche_exacte_employe_jpanel() {
        initComponents();
    }
    public void setEmployeDAO(EmployeDAO empDAO){
        this.empDAO=empDAO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sigle_rech_text = new javax.swing.JLabel();
        idbur_rech_text = new javax.swing.JLabel();
        tel_rech_text = new javax.swing.JLabel();
        desc_rech_text = new javax.swing.JLabel();
        idemp_rech = new javax.swing.JTextField();
        nom_rech = new javax.swing.JTextField();
        matricule_rech = new javax.swing.JTextField();
        pre_rech = new javax.swing.JTextField();
        bt_maj = new javax.swing.JButton();
        bt_rech = new javax.swing.JButton();
        bt_del = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        idbur_rech = new javax.swing.JTextField();

        sigle_rech_text.setText("matricule :");

        idbur_rech_text.setText("idemp :");

        tel_rech_text.setText("nom :");

        desc_rech_text.setText("prenom :");

        idemp_rech.setMinimumSize(new java.awt.Dimension(50, 20));
        idemp_rech.setPreferredSize(new java.awt.Dimension(150, 30));
        idemp_rech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idemp_rechActionPerformed(evt);
            }
        });

        nom_rech.setMinimumSize(new java.awt.Dimension(50, 20));
        nom_rech.setPreferredSize(new java.awt.Dimension(150, 30));

        matricule_rech.setMinimumSize(new java.awt.Dimension(50, 20));
        matricule_rech.setPreferredSize(new java.awt.Dimension(150, 30));

        pre_rech.setMinimumSize(new java.awt.Dimension(50, 20));
        pre_rech.setPreferredSize(new java.awt.Dimension(150, 30));

        bt_maj.setText("Mise à jour");
        bt_maj.setPreferredSize(new java.awt.Dimension(150, 30));
        bt_maj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_majActionPerformed(evt);
            }
        });

        bt_rech.setText("Rechercher");
        bt_rech.setPreferredSize(new java.awt.Dimension(150, 30));
        bt_rech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_rechActionPerformed(evt);
            }
        });

        bt_del.setText("Effaçer");
        bt_del.setPreferredSize(new java.awt.Dimension(150, 30));
        bt_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_delActionPerformed(evt);
            }
        });

        jLabel1.setText("idbur :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_rech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_maj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt_del, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(desc_rech_text)
                            .addComponent(tel_rech_text)
                            .addComponent(sigle_rech_text)
                            .addComponent(idbur_rech_text)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(matricule_rech, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idemp_rech, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nom_rech, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idbur_rech, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pre_rech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(idbur_rech_text))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(idemp_rech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sigle_rech_text)
                    .addComponent(matricule_rech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tel_rech_text)
                    .addComponent(nom_rech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(desc_rech_text)
                    .addComponent(pre_rech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idbur_rech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_maj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_del, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_rech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void idemp_rechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idemp_rechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idemp_rechActionPerformed

    private void bt_majActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_majActionPerformed

        try{
            
            int idemp=Integer.parseInt(idemp_rech.getText());
            String matricule=matricule_rech.getText();
            String nom=nom_rech.getText();
            String pre=pre_rech.getText();
            int idbur=Integer.parseInt(idbur_rech.getText());
            Employe emp=new Employe(idemp,matricule,nom,pre,idbur);
            empDAO.update(emp);
            JOptionPane.showMessageDialog(this,"bureau mis à jour","succès",JOptionPane.INFORMATION_MESSAGE);

        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(),"ERREUR DANS LA MAJ",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bt_majActionPerformed

    private void bt_rechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_rechActionPerformed

        try{
            int idemp=Integer.parseInt(idemp_rech.getText());
            emp=empDAO.read(idemp);
            matricule_rech.setText(emp.getMatricule());
            nom_rech.setText(emp.getNom());
            pre_rech.setText(emp.getPrenom());
            idbur_rech.setText(""+emp.getIdbur());
            
            JOptionPane.showConfirmDialog(this,"bureau trouvé","succès",JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage(),"ERREUR DANS LA RECHERCHE",JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_bt_rechActionPerformed

    private void bt_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_delActionPerformed

        try{
            //int idemp=Integer.parseInt(idemp_rech.getText());
            empDAO.delete(emp);
            idemp_rech.setText("");
            matricule_rech.setText("");
            nom_rech.setText("");
            pre_rech.setText("");
            idbur_rech.setText("");
            
            JOptionPane.showMessageDialog(this,"bureau effacé","succès",JOptionPane.INFORMATION_MESSAGE);

        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage(),"ERREUR DANS LA SUPP",JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_bt_delActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_del;
    private javax.swing.JButton bt_maj;
    private javax.swing.JButton bt_rech;
    private javax.swing.JLabel desc_rech_text;
    private javax.swing.JTextField idbur_rech;
    private javax.swing.JLabel idbur_rech_text;
    private javax.swing.JTextField idemp_rech;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField matricule_rech;
    private javax.swing.JTextField nom_rech;
    private javax.swing.JTextField pre_rech;
    private javax.swing.JLabel sigle_rech_text;
    private javax.swing.JLabel tel_rech_text;
    // End of variables declaration//GEN-END:variables
}
